Re-organizing makefile; Adding LDFLAGS variable; Not needed targets
eafit-apolo/2DPartInt pull request #13
Opened 2019-05-11 22:09 UTC by hamax97

Re-organizing the structure of the makefile so it is easier to read and understand. Also, there where some targets when creating the object files (main.o, functions.o, ...), such as, $(INC_DIR)/data.h $(INC_DIR)/functions.h, which are not needed. The compiler flag -I/include/dir makes the job of including them. In fact, the $< directive in makefiles is to use only the first dependency listed not all the depencies. Therefore, I don't understand why the the other dependencies were there if there were not being used. Also, I added the LDFLAGS variable, which is part of makefiles standards. This variable will help us to link other libraries easier in the future, see https://www2.cs.duke.edu/courses/cps108/doc/makefileinfo/sample.html for more information.

2019-05-11 22:21 UTC, BalmungSan requested changes
> "Re-organizing the structure of the makefile so it is easier to read and understand."

Cool.

> Also, there where some targets when creating the object files (main.o, functions.o, ...), such as, $(INC_DIR)/data.h $(INC_DIR)/functions.h, which are not needed.
> The compiler flag -I/include/dir makes the job of including them. In fact, the $< directive in makefiles is to use only the first dependency listed not all the depencies.
> Therefore, I don't understand why the the other dependencies were there if there were not being used."

Because the targets depends on the headers. If a header is modified _(and the `.c` including is not)_ we still should recompile the object for that `.c` file.
Maybe, it wont work any more, since the imported functions or structures changed their signature.

Not compiling it, and relying on the old `.o` would lead to linking errors which would be harder to debug than normal compile errors. Or, maybe it would compile but will throw segfaults at compile time...
So, It is better to play safe and recompile the source.

Also, as you said the `$<` is used to only pass the first target _(the `.c`)_ given that passing the headers will result in errors.

This is common practice for Makefiles, make the `.o` depend on only one `.c` and a bunch of headers, and use `$<` to only pass the `.c` to the compiler.
And latter combine all `.o` on a exe, using the `$^` to pass all of them.
That is what the autotools would had done.

> "Also, I added the LDFLAGS variable, which is part of makefiles standards. This variable will help us to link other libraries easier in the future."

:+1:

2019-05-12 03:34 UTC, hamax97 commented
> Because the targets depends on the headers. If a header is modified (and the .c including is not) we still should recompile the object for that .c file.
> Maybe, it wont work any more, since the imported functions or structures changed their signature.
If you modify a header file, you **must** recompile all the .c files that use it.
The thing is that I don't understand why to put them as dependencies if we don't use them (in the makefile). IMHO that looks a little ugly, I mean, having something there but not using it. But if you say that it is an standard, ok. I will put them back.

2019-05-12 04:05 UTC, BalmungSan commented
> "If you modify a header file, you must recompile all the .c files that use it".

Exactly.
And how to you accomplish that? By adding the header as a dependency of the target.
Remember that Make is a simple tool, it does known nothing about how the project behaves, it only knows that if any of the dependencies of a target were modified more recently than the target itself, the target should be updated.

2019-05-12 04:07 UTC, BalmungSan approved these changes

2019-05-12 04:08 UTC, merged