WIP: create spatial limits
eafit-apolo/2DPartInt pull request #18
Opened 2019-06-06 01:51 UTC by jandrovins

2019-06-06 03:15 UTC, BalmungSan requested changes

2019-06-06 03:15 UTC, BalmungSan commented on include/functions.h
> +void fix_displacements(const size_t size, Particle *particles, const int n);
Three things.

1. Please, put first all the `const` _arguments_ and then all the **mutable** ones.

2. Touching the limits should also _"stop"_ the particles in the given limit. Thus, you would need the **velocities** too.

3. Add tests!

2019-06-07 02:39 UTC, BalmungSan submitted a review, later dismissed
Being honest, I would create three variables for each diff. As I discourage mutability unless strictly necessary.

But, that is just style, and I see everything else OK.

2019-08-26 02:17 UTC, jandrovins commented
Solved the horizontal limits.

Still cannot be merged due to `nan` values generated in simulation.

2019-09-16 13:13 UTC, closed without merging